version: 2
jobs:
  build:
    docker:
        - image: circleci/node:10.5.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo npm i -g npm
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      # - run:
      #     name: Install npm wee
      #     command: npm install
      - save_cache:m -v
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm install electron-packager -g
      - run: npm install electron-installer-debian -g

workflows:
  version: 2
  init:
    jobs:
      - build
      - test:
          requires:
            - build
  buildAppLinux:
    jobs:
      - electron-packager . --overwrite --platform=linux --arch=x64 --ignore=node_modules/.bin
    requires:
      - init
  testAppLinux:
    jobs:
      - npm run testCI
    requires:
      - buildAppLinux

# - electron-installer-debian --src outflux-linux-x64 --dest linuxInstallers/ --arch amd64
#tag: /v[0-9]+(\.[0-9]+)*/
